<Project>
    <Target Name="ILRepacker" AfterTargets="Build">
        <ItemGroup>
            <InputAssemblies Include="$(TargetPath)" />
            <InputAssemblies Include="$(TargetDir)AnimationSpeedManager.dll" />
            <InputAssemblies Include="$(TargetDir)YamlDotNet.dll" />
        </ItemGroup>
        <ILRepack Parallel="true" DebugInfo="true" Internalize="true" InputAssemblies="@(InputAssemblies)" OutputFile="$(TargetPath)" TargetKind="SameAsPrimaryAssembly" LibraryPath="$(TargetDir);$(CorlibPath);$(PublicizedAssembliesPath);$(BepInExPath)\core" />
    </Target>
</Project>
